# Generated by Django 5.0 on 2024-01-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.BooleanField()),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMinsa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('minimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='via_consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre_generico', models.CharField(max_length=50)),
                ('nombre_cientifico', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('req_receta', models.BooleanField()),
                ('precio', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.categoria')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.laboratorio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.unidad_medida')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.via_consumo')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefarmacia.producto')),
            ],
        ),
    ]
